Modifications
KisiMissi/csv-excel pull request #1
Opened 2023-03-25 02:50 UTC by KisiMissi

# Что было сделано:
- добавлено логирование

## FileHandler
- добавлен тест
- try/catch -> try/catch with resources
- пропуск строки с заголовками через .withSkipLines

## SpreadsheetWriter
- метод tableFilling разбит на более мелкие под методы
- проверка наличия Busy перенесена в BeanListHandler

## BeanListHandler
- логирование непрошедших задач по task id
- Date -> LocalDate
- сравнивание дат происходит через compaerTo
- добавлено условие для задач, которые начинаются раньше нужного срока

2023-03-26 01:31 UTC, progressicu requested changes

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
> +    static {
Достаточно запускать c параметром -Djava.util.logging.config.file = <путь до файла> (как его добавить написано здесь https://www.jetbrains.com/help/idea/run-debug-configuration.html) или один раз сделать как ты, но не в каждом классе

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/in/BeanListHandler.java
> +            }
стоит добавить в конце коммент, что если обе даты меньше с sDate или больше eDate, то задача игнорируется

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/in/FileHandler.java
> +            logger.log(Level.WARNING, "IOException: ", e);
ну ты залогировал и что дальше? Вернется null из этого метода и всё равно программа сломается дальше.
Поэтому тут стоит залогировать и кинуть дальше ошибку, либо не отлавливать её вообще и пусть прокидывается сразу дальше и программа останавливается

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/module/Task.java
> +    @Getter
Чтобы над каждым полем так не делать, то можно над Task просто поставить `@Data`

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/in/FileHandler.java
> +            logger.log(Level.WARNING, "IOException: ", e);
но стоит это сделать не только здесь, а везде где ловишь ошибку - подумать что с ней делать и если от этого программа должна остановиться, то прокинуть наверх, если можешь что-то сделать, то сделать это

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/out/SpreadsheetWriter.java
> +    private static void mainFields(List<Task> taskList, Map<String, Integer> hourlyRate, SheetDefinition s, String section, AtomicInteger rowIndex, AtomicInteger sectionCount, List<Integer> sectionSu
всё равно сложный метод. Надо было лучше оставить как есть, а вот заполнение строки вынести

2023-03-26 01:31 UTC, progressicu commented on src/test/java/org/kaoden/in/FileHandlerTest.java
> +public class FileHandlerTest extends TestCase {
https://www.baeldung.com/junit-5 - вот так лучше использовать junit

2023-03-26 01:31 UTC, progressicu commented on src/test/java/org/kaoden/in/FileHandlerTest.java
> +    public void testReadingFile() {
Тесты пишутся в том числе, чтобы проверить граничные кейсы.

В данном случае тебе не нужно было сюда заносить файл, который я давал.
- Надо было подумать какие кейсы хотелось бы проверить (например, когда одна дата раньше sDate, когда одна дата больше eDate, ...) и на каждый случай написать свой тест и для каждого теста должен быть свой csv (возможно из моего файла), в котором будут только минимум данных, т.е. например только строка с нужным тебе случаем

2023-03-26 01:31 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
>      private static final Map<String, Integer> hourlyRate = new HashMap<>(); // Содержит почасовую ставку
а зачем это тут? Можно было также в методе сделать, писал об этом коммент

2023-04-01 00:30 UTC, progressicu requested changes

2023-04-01 00:30 UTC, progressicu commented on src/main/java/org/kaoden/in/FileHandler.java
> +            logger.log(Level.WARNING, "IOException: ", e);
Всё равно проблема осталось. Почитай best practices по отлову исключений в java.

Давай сделаем более менее правильно и просто - в методах не отлавливай ошибки (но try with resources оставить надо, просто ошибки не отлавливаем) и просто прокидываем их до метода main. А там на весь код будет так сказать глобальный exceptionHandler, т.е. try catch который отлавливает все ошибки, пишет их в лог и останавливает программу

2023-04-01 00:30 UTC, progressicu commented on src/test/java/org/kaoden/in/BeanListHandlerTest.java
> +        // Случай, когда обе даты не попадают в период
Комменты с описанием лучше выносить не в самом методе, а над методом. Типа такого:
   
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/48092349/229256055-5696ebc7-f739-48ef-8302-26476f07f18e.png">

2023-04-01 00:30 UTC, progressicu commented on src/test/java/org/kaoden/in/BeanListHandlerTest.java
> +class BeanListHandlerTest {
замечания ко всем тестам - почитай про AAA (https://freecontent.manning.com/making-better-unit-tests-part-1-the-aaa-pattern/ - хорошая ссылка, но представь что там вместо xUnit будет junit и станет всё понятно)

2023-04-01 00:30 UTC, progressicu commented on src/test/java/org/kaoden/in/BeanListHandlerTest.java
> +        assertEquals(expectedStartDate +"/"+ expectedEndDate,
зачем так делаешь? Делай проще - напиши два assertEquals, в одном сравниваешь одни даты, в другом другие

2023-04-01 00:33 UTC, progressicu commented on src/test/java/org/kaoden/in/BeanListHandlerTest.java
> +        assertEquals(expectedStartDate +"/"+ expectedEndDate,
Почитай про различные принципы (KISS, SOLID, DRY, ...). Твой код должен быть простым, его должен понять любой и он должен быть красивым

2023-04-02 00:56 UTC, KisiMissi commented on src/main/java/org/kaoden/in/FileHandler.java
> +            logger.log(Level.WARNING, "IOException: ", e);
Я правильно понимаю, что в тестах тогда тоже надо обрабатывать эту ошибку, если она пробрасывается наверх?

2023-04-02 23:16 UTC, progressicu commented on src/main/java/org/kaoden/in/FileHandler.java
> +            logger.log(Level.WARNING, "IOException: ", e);
ну также выше прокидываешь, да и всё. 
Либо если хочешь проверить, что будет прокинута определенная ошибка, т.е. в самом тесте вызываешь действие которое точно кинет ошибку при таких данных, то можно проверить, что эта ошибка именно та, которая нужна (https://www.baeldung.com/junit-assert-exception)

2023-04-22 11:32 UTC, progressicu approved these changes

2023-04-24 08:51 UTC, merged